// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsK0cWmFDkoqO4Z9UKlSadqF6g0w0iaec',
    appId: '1:347561883186:web:dd78a2e8124edd96e16e2b',
    messagingSenderId: '347561883186',
    projectId: 'fila-66622',
    authDomain: 'fila-66622.firebaseapp.com',
    storageBucket: 'fila-66622.appspot.com',
    measurementId: 'G-T9QRQQ2GL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNjgZ5ZSOFXPqiOZW64t41lNUAI0KMNDA',
    appId: '1:347561883186:android:58bc957b69adbdabe16e2b',
    messagingSenderId: '347561883186',
    projectId: 'fila-66622',
    storageBucket: 'fila-66622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEamAoyxHzsYmhIxUpASsGMfPkc8A00tY',
    appId: '1:347561883186:ios:a00a45efd6565a23e16e2b',
    messagingSenderId: '347561883186',
    projectId: 'fila-66622',
    storageBucket: 'fila-66622.appspot.com',
    iosBundleId: 'com.example.noFila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEamAoyxHzsYmhIxUpASsGMfPkc8A00tY',
    appId: '1:347561883186:ios:8b73ba0e5c79014ce16e2b',
    messagingSenderId: '347561883186',
    projectId: 'fila-66622',
    storageBucket: 'fila-66622.appspot.com',
    iosBundleId: 'com.example.noFila.RunnerTests',
  );
}
